#!/bin/bash

x=$PWD
p=~/projects/argocd
p-universum=~/projects/argocd-universum

echo
echo "Updating $p"
echo

cd $p
git status
git remote update && git pull

echo && echo "DONE updating: $p"

echo && echo "Updating ${p-universum}"
echo

cd ${p-universum}
git status
git remote update && git pull
