#!/bin/bash

echo
echo "Launching dropbox..."
caja-dropbox start
echo
echo "Beginning to watch the status..."
# The comma here is used as the decimal point. Replace it with dot at your convenience.
watch -n 0,5 caja-dropbox status

echo "Terminated the watch."

echo "Stopping dropbox..."
caja-dropbox stop

echo "Disabling autostarting of dropbox..."
caja-dropbox autostart n
echo "End."
echo
