#!/bin/bash

echo
echo "[Inquiring repository origin]"
echo "Going into every directory here."
echo

for x in *;
do
  if [ -e "${x}"/.git ]
  then
      cd "${x}"
      echo "${x}"
      echo "======================"
      echo "Calling git remote -v ..."
      git remote -v
      echo
      cd ../
  fi
done
