#!/bin/bash

echo
echo "[git status]"
echo "Going into every directory here."
echo

for x in *;
do
  if [ -e "${x}"/.git ]
  then
	cd "${x}"
	echo "${x}"
	echo "======================"
	echo "Calling git status ..."
	git status
	echo
	cd ../
  fi
done
